#ifndef CONSTANTS_CARDS_H
#define CONSTANTS_CARDS_H

enum Cards {
	CARD_NONE,
	CARD_ABANDONED_OUTPOST,
	CARD_ABANDON_HOPE,
	CARD_ABBEY_GARGOYLES,
	CARD_ABBEY_MATRON,
	CARD_ABDUCTION,
	CARD_ABEYANCE,
	CARD_ABJURE,
	CARD_ABOLISH,
	CARD_ABOMINATION,
	CARD_ABOROTH,
	CARD_ABOSHAN_CEPHALID_EMPEROR,
	CARD_ABOSHANS_DESIRE,
};

#endif // CONSTANTS_CARDS_HCARDS_H