#ifndef CONSTANTS_SUPERTYPES_H
#define CONSTANTS_SUPERTYPES_H

#define SUPERTYPE_NONE		0x00
#define SUPERTYPE_BASIC		0x01
#define SUPERTYPE_SNOW		0x02
#define SUPERTYPE_WORLD		0x04
#define SUPERTYPE_LEGENDARY	0x08

#define ENCODE_SUPERTYPES(a, b) (a | b)

#endif // CONSTANTS_SUPERTYPES_H